base_path: .
base_url: 'https://ONEARMY.crowdin.com'
preserve_hierarchy: true
files:
  - source: /docs/**/*.md
    translation: /website/translated_docs/%two_letters_code%/%original_file_name%
  - source: /website/i18n/en.json
    translation: /website/i18n/%locale%.json
